import cv2
import io
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Image as RLImage,
    Table, TableStyle
)


def _cv2_to_rl_image(bgr_image, width_cm=8):
    """Convert an OpenCV BGR image into a ReportLab Image flowable
    via an in-memory PNG buffer (no temp files needed)."""

    success, buf = cv2.imencode(".png", bgr_image)

    if not success:
        return None

    image_stream = io.BytesIO(buf.tobytes())

    return RLImage(image_stream, width=width_cm * cm,
                    height=width_cm * cm)


def generate_pdf_report(output_path, images: dict, metrics: dict,
                         principles: list):
    """Build a Kolam analysis PDF report.

    images: dict of label -> BGR numpy image
        expected keys: 'original', 'recreated', 'difference'
    metrics: dict of metric label -> value
    principles: list of identified design principle strings
    """

    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        topMargin=1.5 * cm,
        bottomMargin=1.5 * cm
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "TitleStyle",
        parent=styles["Title"],
        fontSize=20,
        spaceAfter=6
    )

    subtitle_style = ParagraphStyle(
        "SubtitleStyle",
        parent=styles["Normal"],
        fontSize=10,
        textColor=colors.grey,
        spaceAfter=16
    )

    heading_style = styles["Heading2"]

    story = []

    story.append(Paragraph("Kolam Design Principle Analyzer", title_style))
    story.append(Paragraph(
        f"Analysis Report &bull; Generated on "
        f"{datetime.now().strftime('%d %b %Y, %I:%M %p')}",
        subtitle_style
    ))

    # --- Images section ---
    story.append(Paragraph("Visual Analysis", heading_style))
    story.append(Spacer(1, 8))

    image_row = []
    captions = []

    for key, caption in [
        ("original", "Original Image"),
        ("recreated", "Recreated Kolam"),
        ("difference", "Difference Heatmap")
    ]:
        if key in images and images[key] is not None:
            rl_img = _cv2_to_rl_image(images[key], width_cm=5.5)
            if rl_img is not None:
                image_row.append(rl_img)
                captions.append(Paragraph(
                    f"<para align='center'>{caption}</para>",
                    styles["Normal"]
                ))

    if image_row:
        img_table = Table([image_row, captions])
        img_table.setStyle(TableStyle([
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ]))
        story.append(img_table)

    story.append(Spacer(1, 20))

    # --- Metrics table ---
    story.append(Paragraph("Analysis Metrics", heading_style))
    story.append(Spacer(1, 8))

    table_data = [["Metric", "Value"]]
    for k, v in metrics.items():
        table_data.append([str(k), str(v)])

    metrics_table = Table(table_data, colWidths=[8 * cm, 8 * cm])
    metrics_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#4B3F72")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CCCCCC")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1),
         [colors.white, colors.HexColor("#F5F5F5")]),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))

    story.append(metrics_table)
    story.append(Spacer(1, 20))

    # --- Design principles ---
    story.append(Paragraph("Design Principles Identified", heading_style))
    story.append(Spacer(1, 8))

    for p in principles:
        story.append(Paragraph(f"&#8226; {p}", styles["Normal"]))

    story.append(Spacer(1, 20))
    story.append(Paragraph(
        "Generated by the Kolam Design Principle Analyzer &mdash; "
        "a Computer Vision based system for analyzing traditional "
        "Tamil Kolam art.",
        subtitle_style
    ))

    doc.build(story)

    return output_path
